<?php if($this->getConfig('enabled')){ // start enable module?>
	<?php
		function cut_string_featuredslider($string,$number){
			if(strlen($string) <= $number) {
				return $string;
			}
			else {	
				if(strpos($string," ",$number) > $number){
					$new_space = strpos($string," ",$number);
					$new_string = substr($string,0,$new_space)."..";
					return $new_string;
				}
				$new_string = substr($string,0,$number)."..";
				return $new_string;
			}
		}
	?>
	<?php $this->getProducts() ?>
	<?php $_productCollection=$this->getProductCollection() ?>
	<div class="ma-featured-slider-contain">  <!-- start mt products list -->
		<?php				
			$width_slider = $this->getConfig('width_slider');
			$height_slider = $this->getConfig('height_slider');
			$items = $this->getConfig('items');
			$w_item = $width_slider/$items;
			$qty = $this->getConfig('qty');
			if ( !$this->getConfig('width_thumbnail') ){
				$w_thumbnail = 135;
			} else {
				$w_thumbnail = $this->getConfig('width_thumbnail');
			}
			if( !$this->getConfig('height_thumbnail') ){
				$h_thumbnail = 135;
			 }
			else {
				$h_thumbnail = $this->getConfig('height_thumbnail');
			}
		?>
		<?php if($this->getConfig('title')){?>
			<div class="ma-featured-sldier-title"><h2><?php echo $this->getConfig('title')?></h2></div>
		<?php }?>
		<?php if(!$_productCollection->count()): ?> <!-- start if exist product -->
			<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
		<?php else: ?>
			<div class="ma-featured-slider">			
				<ul id ="ma-featuredpro-slider" class="featured-slider">
					<?php $_collectionSize = $_productCollection->count() ?>
					<?php if( !$this->getConfig('items') ) { $_columnCount = 1 ; } else { $_columnCount = $this->getConfig('items'); }?>
					<?php $i=1; foreach ($_productCollection as $_product): ?>
						<li class="item <?php if($i==1): ?> first<?php elseif($i == $_collectionSize): ?> last<?php endif; ?>" style="width:<?php echo $w_item; ?>px">																																																																				              
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w_thumbnail, $h_thumbnail); ?>" width="<?php echo $w_thumbnail?>" height="<?php echo $h_thumbnail?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></a>
							<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h2>
							<?php $i++; ?>
							<?php if ( $this->getConfig('review') ): ?>
								<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
							<?php endif; ?>
							<?php if( $this->getConfig('price') ): ?>
								<?php echo $this->getPriceHtml($_product, true) ?>
							<?php endif; ?>
							<div class="actions">
								<?php if ($this->getConfig('addtocart')) { ?>
									<?php if($_product->isSaleable()): ?>
										<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
									<?php else: ?>
										<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									<?php endif; ?>
								<?php }?>
								<?php if( $this->getConfig('addtowishlist') || $this->getConfig('addtocompare')){?>
									<ul class="add-to-links">
										<?php if( $this->getConfig('addtowishlist')){?>
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
										<?php endif; ?>
										<?php } ?>
										<?php if( $this->getConfig('addtocompare') ){?>
										<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
											<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
										<?php endif; ?>
										<?php }?>
									</ul>
								<?php }?>
								<?php if( $this->getConfig('description')){?>
									<div class="ma-desc">
										<?php if(!$this->getConfig('maxlength')){?>
											<?php echo nl2br($this->htmlEscape($_product->getShortDescription())) ?>
										<?php } else {?>
											<?php echo nl2br(cut_string_featuredslider($this->htmlEscape($_product->getShortDescription()),$this->getConfig('maxlength'))) ?>			            
										<?php }?>			                    
									</div>
								<?php }?>
							</div>
						</li>
					<?php endforeach ?>
				</ul>
				<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
				<div style="display: none;"><a href="http://www.magentothem.com/" title="Magento Themes">Magento Themes</a></div>
				<div style="display: none;"><a href="http://www.plazathemes.com/" title="Magento Themes">Magento Themes</a></div>
				<div style="display: none;"><a href="http://www.magentothemess.com/" title="Magento Themes">Magento Themes</a></div>
				<div style="display: none;"><a href="http://www.ecomthemes.com/" title="Magento Themes">Magento Themes</a></div>
				<script type="text/javascript">
					function mycarousel_initCallback(carousel)
					{
						// Disable autoscrolling if the user clicks the prev or next button.
						carousel.buttonNext.bind('click', function() {
							carousel.startAuto(0);
						});					
						carousel.buttonPrev.bind('click', function() {
							carousel.startAuto(0);
						});					
						// Pause autoscrolling if the user moves with the cursor over the clip.
						carousel.clip.hover(function() {
							carousel.stopAuto();
						}, function() {
							carousel.startAuto();
						});
					};					
					$bn1(document).ready(function() {
						$bn1('#ma-featuredpro-slider').jcarousel({
							auto: <?php echo $this->getConfig('auto');?>,
							wrap: 'circular',
							animation: <?php echo $this->getConfig('animation'); ?>,
							scroll: <?php echo $this->getConfig('items_scroll');?>,
							initCallback: mycarousel_initCallback
						});
					});
					$bn1(".ma-featured-slider-contain")
						.css("width","<?php echo $width_slider; ?>px")
						.css("height","<?php echo $height_slider; ?>px");
				</script>
			</div>		
		<?php endif; ?> <!-- end exist product -->
	</div> <!-- end products list -->
<?php } ?>


