<?php $posts = $this->getPosts(); ?>
<?php foreach ($posts as $post): ?>
<div class="postWrapper">
     <div class="postTitle">
        <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle();?></a></h2>
    </div>
    <div class="postContent"><?php echo $post->getPostContent(); ?></div>
	
	<?php echo $this->getBookmarkHtml($post) ?>
	<div class="tags"><?php echo $this->getTagsHtml($post) ?></div>
	<div class="postDetails">
		<?php if($this->getCommentsEnabled()): ?>
		<?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" >Comments</a> | 
		<?php endif; ?>
		<?php $postCats = $post->getCats(); ?>
		<?php if(!empty($postCats)):?>
			<?php foreach($postCats as $title=>$url): ?>
			<?php endforeach;?> 
        <?php else:?>
        <?php endif;?></div>
</div>
<?php endforeach; ?> 
<?php $this->getPages(); ?>
