<style>
td.file_label{
	width:50px;
	vertical-align: top;
}

.file_title{
	min-width:300px;
}
</style>
<div class="entry-edit-head">
	<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('File upload') ?></h4>
</div>

<div class="grip np ">
	<div class="fieldset">

		<table cellspacing="0" class="form-list" border="0">
            <tbody>
				<tr>
					<td class="file_label use-default"><label for="file_title" class="normal"><?php echo $this->__('Title'); ?></label></td>
					<td style="vertical-align:middle"><input maxlength="150"  class="file_title" name="file_title" type="text"
value="<?php if ($quote['file_title']) { echo $this->htmlEscape($quote['file_title']); } ?>" />
					</td>
				</tr>
				<?php
				$path = Mage::helper('qquoteadv')->isValidHttp($quote['path']);
				$urlPath = $filePath = '';
				if (empty($path)) {
					$filePath = $quote['path'];
				} else {
					$urlPath = $path;
				}
				?>

				<tr>
					<td class="fl use-default"><input id="idUrl" name="path_info" type="radio" value="url"
<?php if (!empty($urlPath)): ?> checked="checked" <?php endif ?> />&nbsp;<?php echo $this->__('Url'); ?>
					</td>

					<td style="vertical-align:middle"><input class="file_title" type="text" name="url_path"  id="url_path"
						onclick="if($('idUrl')) $('idUrl').checked=true; if($('idFile')) $('idFile').checked=false;"
value="<?php if (!empty($urlPath)) { echo $quote['path']; } ?>" />
					</td>
				</tr>
				<tr>
					<td class="fl use-default"><input id="idFile" name="path_info" type="radio" value="file"
					<?php if (!empty($filePath)): ?> checked="checked" <?php endif ?>/>&nbsp;<?php echo $this->__('File'); ?>
					</td>

					<td style="vertical-align:middle"><input type="file" name="file_path"
						onclick="if($('idUrl')) $('idUrl').checked=false; if($('idFile')) $('idFile').checked=true;">
<?php
if (!empty($filePath)) {
	$path = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $filePath;
	echo '<br /><a href="' . $path . '">' . $filePath . '</a>';
}
?>
					</td>
				</tr>
        </table>

	</div>
</div>