<div class="entry-edit-head">
	<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Shipping information') ?></h4>
</div>
<div id="_newsletterbase_fieldset" class="fieldset">
    <div class="hor-scroll">
    <?php
    $spanStyle      = '';
    $inputDisplay   = '';

    if(!$this->isAvaliableShipPrice()){  $spanStyle='style="display:none;"'; }
    if(!$this->isAvaliableShipPrice() || empty($quote['shipping_type']) ){ $inputDisplay='disabled="disabled"'; }


    $sPrice = '
        <span '.$spanStyle.' id="shipping" >
                    <label for="shipping_price" class="normal">'.$this->__('Price').'</label> <span class="required">*</span>
                    <input type="text" value="'.$this->getQuoteShipPrice().'" size="3"  id="shipping_price" name="shipping_price"
         '.$inputDisplay.'   style="width:70px;"
        	class="required-entry validate-zero-or-greater required-entry input-text"  />

        </span>';
    ?>




<table cellspacing="0" class="form-list" border="0">
            <tbody>

            <tr>
                <td class="label">
                    <label for="shipping_type" class="normal"><?php echo $this->__('Use Store settings'); ?></label>
                </td>
                <td style="width:50px; vertical-align:middle;"><input name="shipping_type" type="radio" value="" <?php if(empty($quote['shipping_type'])):?>checked="checked"<?php endif; ?>
        					onclick="
       if(this.checked) {
                shipI = $('shipI').innerHTML;
                shipO = $('shipO').innerHTML;
                if(shipI.length>5){
                    $('shipEmpty').innerHTML = shipI;
                    $('shipI').innerHTML='';
                }
                else if(shipO.length>5)
                {
                    $('shipEmpty').innerHTML = shipO;
                    $('shipO').innerHTML='';
                }

                $('shipping_price').disabled=true;
               // $('shipping_price').value='';
                $('shipping').hide();
       }
        "

        					 /></td>
                <td style="vertical-align:middle;"><span id="shipEmpty"><?php if( empty($quote['shipping_type']) ) echo $sPrice; ?></span></td>
            </tr>
             <tr>
                <td class="label">
                <label for="shipping_type" class="normal"><?php echo $this->__('Per Item'); ?></label>

                </td>
                <td style="vertical-align:middle;"><input name="shipping_type" type="radio" value="I" <?php if($quote['shipping_type']=='I'): ?>checked="checked"<?php endif; ?>
        					 onclick="
         if(this.checked) {

                $('shipping_price').disabled=false;

                $('shipping').show();

                shipEmpty = $('shipEmpty').innerHTML;
                shipO = $('shipO').innerHTML;

                if(shipEmpty.length>5){
                    $('shipI').innerHTML = shipEmpty;
                    $('shipEmpty').innerHTML='';
                }
                else if(shipO.length>5)
                {
                    $('shipI').innerHTML = shipO;
                    $('shipO').innerHTML='';
                }

        }
        "
        					 /></td>
                <td style="vertical-align:middle;"><span id="shipI"><?php if( $quote['shipping_type']== 'I') echo $sPrice; ?></span></td>
            </tr>
            <tr>
                <td class="label">
                <label for="shipping_type" class="normal"><?php echo $this->__('Fixed price per Order'); ?></label>

                </td>
                <td style="vertical-align:middle;"><input name="shipping_type" type="radio" value="O" <?php if($quote['shipping_type']=='O'): ?>checked="checked"<?php endif; ?>
        					 onclick="
         if(this.checked) {

               $('shipping_price').disabled=false;

               $('shipping').show();

               shipEmpty = $('shipEmpty').innerHTML;
               shipI = $('shipI').innerHTML;

                if(shipI.length>5){
                    $('shipO').innerHTML = shipI;
                    $('shipI').innerHTML='';
                }
                else if(shipEmpty.length>5)
                {
                    $('shipO').innerHTML = shipEmpty;
                    $('shipEmpty').innerHTML='';
                }
        }
        "

        					  /></td>
            <td style="vertical-align:middle;"><span id="shipO"><?php if( $quote['shipping_type']== 'O') echo $sPrice; ?></span>
            </td>

            </tr>
        </table>
	</div>
</div>	