<?php
/**
 * Manufacturers extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   FME
 * @package    Manufacturers
 * @author     Kamran Rafiq Malik <kamran.malik@unitedsol.net>
 * @copyright  Copyright 2010 © free-magentoextensions.com All right reserved
 */
?>
<link type="text/css" href="<?php echo $this->getSkinUrl(); ?>/css/faqs/accordion.css" rel="stylesheet">
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/faqs/jquery.js"></script>
<script type="text/javascript">
jQuery(function($) {	
	$(".accordion3 h3").eq(2).addClass("active");
	$(".accordion3 p").eq(2).show();
	$(".accordion3 h3").click(function(){
		$(this).next("p").slideToggle("slow")
		.siblings("p:visible").slideUp("slow");
		$(this).toggleClass("active");
		$(this).siblings("h3").removeClass("active");
	});

});
jQuery.noConflict();
</script>
<?php 
$topics = $this->getTopics();
?>
<div class="page-title">
   <h1><?php echo Mage::helper('faqs')->__('FAQ\'s Categories') ?></h1>
</div>
<?php if ( count($topics) == 0 ) : ?>    
		<p class="empty"><?php echo Mage::helper('faqs')->__('No Category find yet!') ?></p>
<?php else : ?>
	<div class="accordion4"> 
		 <?php foreach ($topics as $_topic): ?>
				<h3><a href="<?php echo Mage::helper('faqs')->getUrl($_topic['identifier']); ?>"><?php echo $_topic["title"]; ?></a></h3>
		 <?php endforeach; ?>
	</div>
<?php endif; ?>