<?php if($this->getConfig('enabled')){ ?>	  <!-- start enable -->
	<div class="ma-banner1-container">
        <div class="ma-banner1">					
			<div id="slideshowHolder">
				<?php
					// Get data banner
					$slide = $this->getDataBanner1();
					$path = Mage::getBaseUrl('media');					
					$width = $this->getConfig('width');
					$height = $this->getConfig('height');
					$speed = $this->getConfig('speed');
					$interval = $this->getConfig('interval');
					$qty_Item = $this->getConfig('qty_item');
					$mode = $this->getConfig('animation');					
					switch ( $mode ) {
						case 'animation4': $effect = 'wave'; break;
						case 'animation5': $effect = 'zipper'; break;
						case 'animation6': $effect = 'curtain'; break;
					}					
					/* Get max item & qty item */
					if ($qty_Item > count($slide)) {
						$qty_Item = count($slide);
					}
				?>
				<?php
					$i = 1;
					foreach($slide as $s)
					{
						if($i <= $qty_Item) {
							//Get images slide show
							$st1 = $s['image'];
							$p1 = strpos($st1,'banner1');
							$st2 = substr($st1,$p1+7);
							$p2 = strpos($st2,'"');
							$imag = substr($st2,0,$p2);
					?>				
							<?php if( $s['link'] ) { ?>
								<a href="<?php echo $s['link']?>" title=""><img src="<?php echo $path.'magentothem/banner1'.$imag;?>" width="<?php echo $width;?>" height="<?php echo $height;?>" alt="" /></a>												
							<?php } else { ?>
								<img src="<?php echo $path.'magentothem/banner1'.$imag;?>" width="<?php echo $width;?>" height="<?php echo $height;?>" alt="" />
							<?php } ?>
					<?php
                        }//end if
                    $i++;
                    } // end foreach
				?>
            </div>
            <script type="text/javascript">
				$bn1(".ma-banner1")
						.css("width","<?php echo $width; ?>px")
						.css("height","<?php echo $height; ?>px");
                $bn1('#slideshowHolder').jqFancyTransitions({ 
                    effect: '<?php echo $effect; ?>', // wave, zipper, curtain
                    width: <?php echo $width; ?>, // width of panel
                    height: <?php echo $height; ?>, // height of panel
                    titleSpeed: <?php echo $speed; ?>, // speed of title appereance in ms
                    delay: <?php echo $interval; ?>, // delay between images in ms
                    stripDelay: 50, // delay beetwen strips in ms
                    strips: 15, // number of strips
                    titleOpacity: 0.7, // opacity of title
                    position: 'alternate', // top, bottom, alternate, curtain
                    direction: 'fountainAlternate', // left, right, alternate, random, fountain, fountainAlternate
                    navigation: true, // prev and next navigation buttons
                    links: false // show images as links
                });
				<?php if( !$this->getConfig('next_back')){ ?>
                    //<![CDATA[
						$bn1("head").append('<style type="text/css"> .ft-prev, .ft-next { display: none; }</style>');
					//]]>
				<?php } ?>
				<?php if( !$this->getConfig('nav_ctrl')){ ?>
                    //<![CDATA[
						$bn1("head").append('<style type="text/css"> #ft-buttons-slideshowHolder { display: none; }</style>');
					//]]>
				<?php } ?>				
            </script>
		</div>
		<div style="display: none;"><a href="http://www.magentothem.com/" title="Magento Themes">Magento Themes</a></div>
		<div style="display: none;"><a href="http://www.plazathemes.com/" title="Magento Themes">Magento Themes</a></div>
		<div style="display: none;"><a href="http://www.magentothemess.com/" title="Magento Themes">Magento Themes</a></div>
    </div>
<?php } ?> <!-- end enable -->