<?php
	$data	=	$this->getLoadedProductCollection();
	
    $_helper = $this->helper('catalog/output');	
?>
<?php if(count($data) == 0): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products pwb-category-products ">    
	<div></div>
    <?php $_collectionSize = $data->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0;$j=0; foreach ($data as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="actions pwb-actions">
                    <?php if($_product->isSaleable()): ?>
						<form class="pwb_form_quality" action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form<?php echo $j; ?>" name="product_addtocart_form<?php echo $j; ?>">                               
							<?php if(!$_product->isGrouped()): ?>                                 
							<span class="addToBox">
							<?php //echo $this->__('Qty:') ?> 
							<input name="qty" type="text" class="input-text qty" maxlength="5" value="<?php echo $this->getMinimalQty($_product)== null?1:$this->getMinimalQty($_product) ?>"/> 
							<?php endif; ?>
							</span>
						</form>
					<a class="add_to_cart button btn-cart" href="javascript:void(0);" onclick="qtyForm('product_addtocart_form<?php echo $j; ?>'); return false;"><span><span><?php echo $this->__('Add to Cart') ?></span></span></a> 
						
                      <!--  <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>-->
                    <?php $j= $j+1; else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        <?php 
		$config	=	$this->getConfigs();
		if($config['toolbar']	==	1)
		{
			$pager = $this->getLayout()->createBlock('page/html_pager');
			echo $this->getToolbarBlock()->setCollection($data)->setTemplate('em_productsfilterwidget/toolbar.phtml')->setChild('product_list_toolbar_pager',$pager)->toHtml(); 
		}		
	 ?> 

<script type="text/javascript" language="javacript" >
	function qtyForm(elm){
		document.forms[elm].submit();
	}
	
	jQuery(document).ready(function(jQuery) {
		jQuery('.pwb_form_quality').each(function(){
			jQuery(this).append('<div class="inc buttonnum">+</div><div class="dec buttonnum">-</div>');
		});
		jQuery(".buttonnum").click(function() {
			var $button = jQuery(this);
			var oldValue = $button.parent().find("input").val();
		
			if ($button.hasClass('inc')) {
			  var newVal = parseFloat(oldValue) + 1;
			  // AJAX save would go here
			} else {
			  // Don't allow decrementing below zero
			  if (oldValue > 1) {
				  var newVal = parseFloat(oldValue) - 1;
				  // AJAX save would go here
			  }
			}
			$button.parent().find("input").val(newVal);
		});

	});
	
</script> 
</div>
    <?php endif; ?>
	



