<?php
/**
* J!Code WebDevelopment
*
* @title 		Magento payment module for iDeal Advanced
* @category 	J!Code
* @package 		Jcode_Community
* @author 		Jeroen Bleijenberg / J!Code WebDevelopment <support@jcode.nl>
* @license  	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
?>
<?php $_code=$this->getMethodCode() ?>
<?php if($_issuers = $this->getIssuerList()):?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_ideal_issuer_id"><?php echo $this->__('Issuer') ?> <span class="required">*</span></label><br/>
                <select id="<?php echo $_code ?>_ideal_issuer_id" name="payment[ideal_issuer_id]" class="required-entry">
                    <option value="">--<?php echo $this->__('Please Select') ?>--</option>
                <?php foreach ($_issuers as $_id => $_name): ?>
                    <option value="<?php echo $_id ?>"><?php echo $_name ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </li>
    </ul>
</fieldset>
<?php endif?>