<?php
/**
* J!Code WebDevelopment
*
* @title 		Magento payment module for iDeal Advanced
* @category 	J!Code
* @package 		Jcode_Community
* @author 		Jeroen Bleijenberg / J!Code WebDevelopment <support@jcode.nl>
* @license  	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
?>
<?php if($_info = $this->getInfo()): ?>
<?php echo $this->getMethod()->getTitle() ?>
<br />
<?php echo $this->__('Issuer'). ': ' . $this->getIssuerTitle() ?>
<?php else: ?>

<?php endif; ?>